export const ADD_PLAYLIST = "CHANGE_PLAYLIST";
export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG";
export const CHANGE_CURRENT_SONG_INDEX = "CHANGE_CURRENT_SONG_INDEX";
export const CHANGE_CURRENT_PLAY_STATUS = "CHANGE_CURRENT_PLAY_STATUS";

export const CHANGE_THE_SONG_DETAIL = "CHANGE_THE_SONG_DETAIL";
export const CHANGE_THE_SONG_LYRICS = "CHANGE_THE_SONG_LYRICS";
export const CHANGE_THE_SONG_COMMENTS = "CHANGE_THE_SONG_COMMENTS";